apps/example-app/src/app/examples/product-picker-page/components/product-select-dialog/product-select-dialog.component.ts
apps/example-app/src/app/examples/product-picker-page/components/product-select-dialog/products.traits.ts
libs/ngrx-traits/src/lib/create-entity-feature.spec.ts
libs/ngrx-traits/src/lib/local-store/README.md
libs/ngrx-traits/src/lib/local-store/traits-local-store.spec.ts
libs/ngrx-traits/src/lib/local-store/traits-local-store.ts
libs/ngrx-traits/testing/src/provide-mock-local-traits.ts

Refactor to ease implementation of local traits by allowing effects to be declared inside the class that extends TraitsLocalStore

feat(local-traits): allow effects to be declared directly in the service of the local traits

---

libs/ngrx-traits/src/lib/create-entity-feature.spec.ts
libs/ngrx-traits/src/lib/create-entity-feature.ts

allow entity names param to be optional, it doesn't make sense in  cases that don't use any of the traits that load entities like addAsyncActions

feat(createentityfeature): make entity names optional

---

apps/example-app/src/app/examples/product-picker-page/components/product-select-dialog/product-select-dialog.component.ts
apps/example-app/src/app/examples/product-picker-page/components/product-select-dialog/products.traits.ts
libs/ngrx-traits/src/lib/create-entity-feature.spec.ts
libs/ngrx-traits/src/lib/local-store/README.md
libs/ngrx-traits/src/lib/local-store/traits-local-store.spec.ts
libs/ngrx-traits/src/lib/local-store/traits-local-store.ts

The previous feature to enable writing effects inside the LocalTraits brough a race condition that
makes the effects of the LocalTraits not be initialized when the component ngOnit was call this was
do to using the queueMicroTask to register services

fix(local-traits): rollback allow writing effects inside TraitsLocal

---

apps/example-app/src/app/examples/signals/infinete-scroll-page/products-branch.store.ts
apps/example-app/src/app/examples/signals/product-shop-page/products-shop.store.ts
libs/ngrx-traits/signals/api-docs.md
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.ts

the factory function config will receive the store, and allow access to it in the fetchEntities,
onSuccess and onErrors methods
Fix #95

 feat(signals): allow withEntitiesLoadingCall to receive a factory function for config

---

libs/ngrx-traits/signals/api-docs.md
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.model.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.spec.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts

Removes the `first()` operator from the `withCalls` response pipe. Allowing observables that emit multiple values to be returned, with an initial loading state and then no further loading state until the params trigger a new request.
*Warning:* Potentially breaking change, as if the response does not complete, then the default `exhaustMap` operator will mean that subsequent triggers are ignored. The solution is to either use `switchMap` or ensure that you complete.
@gabrielguerrero Keen to discuss whether `exhaustMap` is still the best default operator. Or whether you want different behaviour depending on whether the call is promise-returning or observable-returning? One other idea is that we could add a check that if the call returns an observable and doesn't complete after the first …

Don't unsubscribe from response observable after first response

---

libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.spec.ts

fix for withEntitiesSingleSelection to remove params of deselectEntity and
deselect[Collection]Entity
fix #112

fix(signals): fix withEntitiesSingleSelection deselect methods type

---

libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-filter.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-remote-sort.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-remote-sort.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-remote-sort.ts

New param triggerLoadingCall for filterEntities, sortEntities and loadEntitiesPage to disable auto
calling set loading automatically, necessary to better control when the loading happens
fix #114

 feat(signals): add triggerLoadingCall to remote filter, sort and pagination

---

.github/workflows/build.yml
apps/example-app/src/app/app.module.ts
apps/example-app/src/app/examples/signals/product-list-paginated-page/product.store.ts
libs/ngrx-traits/signals/api-docs.md
libs/ngrx-traits/signals/src/lib/index.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-filter.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.ts
libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.util.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-entities-sync-to-route-query-params.spec.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-entities-sync-to-route-query-params.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-sync-to-route-query-params.spec.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-sync-to-route-query-params.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-sync-to-route-query-params.util.ts

new withSyncToRouteQueryParams store feature that allows to sync parts of the state to the url query
params, and withEntitiesSyncToRouteQueryParams which syncs entities filters, pagination sort and single selection state to the url query params
fix #116

Feat with sync to route query params

---

libs/ngrx-traits/signals/src/lib/with-calls/with-calls.model.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.spec.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts

New enabled function in withCalls config allows to skip the call under certain user defined conditions like when params are null, or result was already cached
fix #134

feat(signals): add enabled function to withCalls config

---

libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts

fix typeCallConfig not removing result prop from types when storeResult:false
fix #136

fix(signals): fix typeCallConfig not removing result prop from types when storeResult:false

---

libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.model.ts

Fix the Sort type of withEntitiesLocalSort, so intelli sence on the field prop of the Sort type , automcompletes the props of the Entity
fix #138

fix(signals): fix Sort model type so it can autocomplet Entity type props

---

libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-filter.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.util.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-entities-sync-to-route-query-params.spec.ts

A bug in withEntitiesSyncToRouteQueryParams, was making it only work if the store have withEntities for all 3 sort, filter and pagination, this fix allows to have any one or two
fix #140

Fix: withEntitiesSyncToRouteQueryParams requires to have sort, filter and pagination

---

libs/ngrx-traits/signals/src/lib/with-call-status/with-call-status.util.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.model.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.spec.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts

Add support for private methods (methods with _ in the start of the name) to withCalls
fix #142

feat(signals): add support for _ method names in withCalls

---

libs/ngrx-traits/signals/api-docs.md
libs/ngrx-traits/signals/src/lib/with-logger/with-state-logger.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-sync-to-route-query-params.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-web-storage/with-sync-to-web-storage.ts

Made the return type explicit for withSyncToWebStorage, withStateLogger and withSyncToRouteQueryParams, before the were inferred which worked fine in the examples inside the project but when compiled as lib, causes a problem were the functions inside the traits can not correctly infer the store , this also fixes using the library with skipLibCheck: false
Fixes #145 , #91

fix(signals): fix return type for some of the traits

---

libs/ngrx-traits/signals/package.json
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.ts
package-lock.json
package.json

- Update @ngrx/signals to version 18.1.0
- Removed unused imports
- Applied deepComputed to non flat computeds:  withEntitiesLocalPagination, withRemotePagination, withEntitiesRemoteScroll

feat(deepComputed): apply deepcomputed to non flat computed

---

libs/ngrx-traits/signals/src/lib/with-calls/with-calls.spec.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts

Due to a bug when using mapPipe: exhaustMap or switchMap was always behaving like a concatMap, this pr fixes the issue and adds tests
fix #148

fix(signals): withCalls mapPipe not working correctly

---

apps/example-app/src/app/examples/signals/product-list-paginated-page/product.store.ts
apps/example-app/src/app/examples/signals/product-list-paginated-page/route-product-detail.component.ts
apps/example-app/src/app/examples/signals/product-list-paginated-page/signal-product-list-paginated-page-container.component.ts
libs/ngrx-traits/signals/src/lib/util.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.model.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.spec.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts

new callWithParams prop allows reactively call the method when other signals or observables change
Fix #151

feat(signals): new callWith prop for withCalls

---

libs/ngrx-traits/signals/api-docs.md
libs/ngrx-traits/signals/src/lib/index.ts
libs/ngrx-traits/signals/src/lib/test.mocks.ts
libs/ngrx-traits/signals/src/lib/test.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-hybrid-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-hybrid-filter.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.spec.ts

New store feature to handle filter cases where some of the filter props should trigger a remote filter and some a local filter
Fix #160

feat(signals): withEntitiesHybridFilter

---

libs/ngrx-traits/signals/src/lib/with-call-status/with-call-status.ts
libs/ngrx-traits/signals/src/lib/with-call-status/with-call-status.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.ts
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-remote-sort.ts

This small refactor fixes a bug causing the swithMap impl not cancel request when new setLoading are trigger.
Fixes #162

fix(signals): fix to withEnttiesLoading mapPipe

---

libs/ngrx-traits/signals/src/lib/with-calls/with-calls.spec.ts
libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts
libs/ngrx-traits/signals/src/lib/with-entities-calls/with-entities-calls.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-calls/with-entities-calls.ts
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.ts
libs/ngrx-traits/signals/src/lib/with-logger/with-logger.ts

Log the error to console.error if in dev mode for withCalls withEntitiesLoading and withEntitiesCalls
Fix #184

feat(signals): improve log of errors for withCalls and others

---

libs/ngrx-traits/signals/src/lib/with-calls/with-calls.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-calls/with-entities-calls.model.ts

callWith should accept true when the call has no params but was not working sometimes
Fix #188

fix(signals): fix callWith type when call has no params

---

libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-hybrid-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-hybrid-filter.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.ts

feat(signals): allow filterEntities to force reapply the previous filter
Now calling filterEntities without params will force apply the previous filter
Fix #194

Allow filterEntities to force reapply the previous filter

---

apps/docs/src/app/pages/docs/traits/with-entities-sync-to-route-query-params.md
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-filter.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.model.ts
libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.util.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-entities-sync-to-route-query-params.spec.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-entities-sync-to-route-query-params.ts

Add optional skipLoadingCall parameter that allows restoring state from query params without triggering backend calls. When set to true, filter, sort, and pagination state will be updated in the store without calling fetchEntities.
This is useful when entities are already loaded, or when you want to defer
API calls until after initialization logic completes.
Fix #216

feat(signals): add skipLoadingCall parameter to withEntitiesSyncToRouteQueryParams

---

libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-filter.util.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-filter.util.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-hybrid-filter.spec.ts
libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.spec.ts

Modify the logic so that the distinctUntilChanged check is bypassed if the previous filterEntities call was made with the skipLoadingCall: true option. This will ensure that the first "real" data request always goes through, even if its filter criteria match a previous "skipped" call.
Fix #219

fix(signals): filterEntities block by previous call with skipLoadingCall true

---

apps/docs/src/app/pages/docs/traits/with-sync-to-web-storage.md
libs/ngrx-traits/signals/src/lib/with-sync-to-web-storage/with-sync-to-web-storage.spec.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-web-storage/with-sync-to-web-storage.ts
libs/ngrx-traits/signals/src/lib/with-sync-to-web-storage/with-sync-to-web-storage.util.ts

Add a new valueMapper option that enables custom bidirectional transformation
between store state and storage values. This provides more flexibility than
filterState by allowing users to transform data format before saving and
reconstruct state when loading.

feat(signals): add valueMapper support to withSyncToWebStorage
