- apps/example-app/src/app/examples/product-picker-page/components/product-select-dialog/product-select-dialog.component.ts
- apps/example-app/src/app/examples/product-picker-page/components/product-select-dialog/products.traits.ts
- libs/ngrx-traits/src/lib/create-entity-feature.spec.ts
- libs/ngrx-traits/src/lib/local-store/README.md
- libs/ngrx-traits/src/lib/local-store/traits-local-store.spec.ts
- libs/ngrx-traits/src/lib/local-store/traits-local-store.ts
- libs/ngrx-traits/testing/src/provide-mock-local-traits.ts
simplify the flow to create local traits by allowing effects inside the traitlocal services
> feat(local-traits): allow effects on traitlocal classes

- libs/ngrx-traits/traits/src/filter-entities/filter-entities.model.ts
- libs/ngrx-traits/traits/src/filter-entities/filter-entities.trait.effect.ts
- libs/ngrx-traits/traits/src/filter-entities/filter-entities.trait.spec.ts
- libs/ngrx-traits/traits/src/filter-entities/filter-entities.trait.ts
New isRemoteFilter function allows to execute a local or remote search depending on the props
changed on the filter
> feat(filter-trait): new isRemoteFiter prop

- .gitignore
- .prettierignore
- libs/ngrx-traits/common/package.json
- libs/ngrx-traits/core/package.json
Fixes wrong dependencies in the v17 packagae .json
> fix(package): fix dependencies of core and common package

- libs/ngrx-traits/signals/project.json
Fix publish of signals package
> fix: fix signals package npm publish config

- libs/ngrx-traits/signals/project.json
Fix publish for signals packagage
> Fix signals package publish

- apps/example-app/src/app/examples/README.md
- docs/signals.md
- libs/ngrx-traits/signals/api-docs.md
- libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.ts
- Add typedCallConfig to withCalls api docs
- Add withCalls to main signal.md
- Add discord link to signal.md
fix #86
> docs(signals): improve docs for withCalls

- libs/ngrx-traits/signals/api-docs.md
- libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts
> docs(signals): fix incorrect text in withCalls doc

- apps/example-app/src/app/examples/signals/product-list-paginated-page/signal-product-list-paginated-page-container.component.ts
- apps/example-app/src/app/examples/signals/product-shop-page/components/product-shop-tab/product-shop-tab.component.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.model.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.util.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.model.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts
> feat(signals): allow loadEntitiesPage to change pageSize

- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts
Fix change page size not working after the second change on the same page
Fix #100
>  fix change page size not working after second change on same page

- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts
fix for withEntitiesRemotePagination bug when last page has 1 item
Fix #106
> fix(signals): fix for withEntitiesRemotePagination bug when last pag

- apps/example-app/src/app/examples/signals/infinete-scroll-page/products-branch.store.ts
- apps/example-app/src/app/examples/signals/product-list-paginated-page/product-custom-Id.store.ts
- docs/signals.md
- libs/ngrx-traits/signals/src/lib/with-call-status/with-call-status.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.ts
- libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.ts
- libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-multi-selection.ts
- libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-remote-sort.ts
Refactor to allow having a custom id using idKey param
Fixes #85
> Allow having a custom id using idKey param

- apps/example-app/src/app/examples/signals/product-list-paginated-page/product.store.ts
- libs/ngrx-traits/signals/package.json
- libs/ngrx-traits/signals/src/lib/with-calls/with-calls.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.ts
- libs/ngrx-traits/signals/src/lib/with-entities-loading-call/with-entities-loading-call.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/signal-infinite-datasource.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-local-pagination.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.ts
- libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-multi-selection.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-multi-selection.ts
- libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-single-selection.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-remote-sort.ts
- libs/ngrx-traits/signals/src/lib/with-event-handler/with-event-handler.ts
- libs/ngrx-traits/signals/src/lib/with-logger/with-state-logger.ts
- libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-entities-sync-to-route-query-params.ts
- libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-sync-to-route-query-params.spec.ts
- libs/ngrx-traits/signals/src/lib/with-sync-to-route-query-params/with-sync-to-route-query-params.ts
- libs/ngrx-traits/signals/src/lib/with-sync-to-web-storage/with-sync-to-web-storage.spec.ts
- libs/ngrx-traits/signals/src/lib/with-sync-to-web-storage/with-sync-to-web-storage.ts
- package-lock.json
- package.json
Support for 18.0.0-rc3, also refactored to no longer using internal types, using new public ngrx signal types
> feat(signals): support ngrx-signals 18.0.0

- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.ts
clearEntitiesCache was not reseting the state correctly
Fix #128
> fix(signals): fix clearEntitiesCache for remote scroll pagination

- libs/ngrx-traits/signals/api-docs.md
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.ts
Allow override the sortFunction used in the entities sort
fix #131
> feat(signals): withEntitiesLocalSort allow custom sort function

- libs/ngrx-traits/signals/src/lib/with-entities-selection/with-entities-multi-selection.ts
- libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-remote-sort.ts
- libs/ngrx-traits/signals/src/lib/with-event-handler/with-event-handler.ts
remove some internal ngrx signals imports
fix ##150
> fix(fix wrong imports): fix wrong imports

- apps/example-app/src/app/examples/signals/product-shop-page/products-shop.store.ts
- libs/ngrx-traits/signals/src/lib/index.ts
- libs/ngrx-traits/signals/src/lib/with-logger/with-logger.spec.ts
- libs/ngrx-traits/signals/src/lib/with-logger/with-logger.ts
- libs/ngrx-traits/signals/src/lib/with-logger/with-logger.util.ts
- libs/ngrx-traits/signals/src/lib/with-logger/with-state-logger.ts
Renamed withStateLogger to withLogger,can long computed props now,  filter function now receives the store, and can log diff of changes
Fix #165
>  feat(signals): withLogger improvements

- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-filter.util.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-hybrid-filter.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-hybrid-filter.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.model.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-local-filter.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.spec.ts
- libs/ngrx-traits/signals/src/lib/with-entities-filter/with-entities-remote-filter.ts
refactor entitiesFilter to use deepComputed
Fix #166
> feat(signals): refactor entitiesFilter to use deepComputed

- libs/ngrx-traits/signals/src/lib/index.ts
- libs/ngrx-traits/signals/src/lib/with-call-status-map/with-call-status-map.model.ts
- libs/ngrx-traits/signals/src/lib/with-call-status-map/with-call-status-map.spec.ts
- libs/ngrx-traits/signals/src/lib/with-call-status-map/with-call-status-map.ts
- libs/ngrx-traits/signals/src/lib/with-call-status-map/with-call-status-map.util.ts
- libs/ngrx-traits/signals/src/lib/with-call-status/with-call-status.model.ts
adds new withCallStatusMap to support calls with a status per id
> feat(signals): withCallStatusMapp

- apps/example-app/src/app/examples/signals/order-list/order-list.store.ts
- libs/ngrx-traits/signals/src/lib/index.ts
- libs/ngrx-traits/signals/src/lib/with-entities-calls/with-entities-calls.model.ts
- libs/ngrx-traits/signals/src/lib/with-entities-calls/with-entities-calls.ts
fix(signals): fix export of with-entities-calls Fix #182
> fix(signals): fix export of with-entities-calls

- libs/ngrx-traits/signals/src/lib/cache/global-cache.ts
fix cacheCall and cacheRxCall return types
> fix(signals): fix cacheCall and cacheRxCall return types

- apps/docs/src/app/pages/docs/traits/with-entities-hybrid-filter.md
- apps/docs/src/app/pages/docs/traits/with-entities-local-filter.md
- apps/docs/src/app/pages/docs/traits/with-entities-remote-filter.md
docs(docs): fix example code typos
```
- Fixes typos withing Filtering documentation pages
Fix #204
```
> docs(docs): fix example code typos

- libs/ngrx-traits/signals/src/lib/index.ts
> fix(signals): export entityCallConfig
